import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatToolbarModule,
  MatIconModule,
  MatBadgeModule,
  MatStepperModule,
  MatCardModule,
  MatCheckboxModule,
  MatMenuModule,
  MatGridListModule,
  MatButtonToggleModule,
  MatSidenavModule,
  MatSelectModule,
  MatTableModule,
  MatPaginatorModule,
  MatRippleModule,
  MatDialogModule,
  MatSlideToggleModule,
  MatChipsModule,
  MatSliderModule,
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatToolbarModule,
    MatIconModule,
    MatBadgeModule,
    MatStepperModule,
    MatCardModule,
    MatCheckboxModule,
    MatMenuModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MatSelectModule,
    MatPaginatorModule,
    MatTableModule,
    MatPaginatorModule,
    MatRippleModule,
    MatDialogModule,
    MatSlideToggleModule,
    MatChipsModule,
    MatSliderModule,
  ],
  exports: [
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatToolbarModule,
    MatIconModule,
    MatBadgeModule,
    MatStepperModule,
    MatCardModule,
    MatCheckboxModule,
    MatMenuModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MatSelectModule,
    MatTableModule,
    MatPaginatorModule,
    MatRippleModule,
    MatDialogModule,
    MatSlideToggleModule,
    MatChipsModule,
    MatSliderModule,
  ]

})
export class AppMaterialModule { }
